export const images = {
  arrowLeft: require('./sources/arrowLeft.png'),
  arrowLeft2: require('./sources/arrowLeft2.png'),
  close: require('./sources/close.png'),
  logo: require('./sources/logo.png'),
  eye: require('./sources/eye.png'),
  arrowLeftCircle: require('./sources/arrow-left-circle.png'),
  arrowRightCircle: require('./sources/arrow-right-circle.png'),
  error: require('./sources/error.png'),
  success: require('./sources/success.png'),
  checked: require('./sources/checked.png'),
  checkbox: require('./sources/checkbox.png'),
  radio: require('./sources/radio.png'),
  radioChecked: require('./sources/radioChecked.png'),
  edit: require('./sources/edit.png'),
};
