export const QUERY_KEY = {
  CURRENT_USER: 'CURRENT_USER',
  ROLES: 'ROLES',
  SITES: 'SITES',
  USERS: 'USERS',
  TAKEN_ACTIONS: 'TAKEN_ACTIONS',
  INCIDENT_TYPES: 'INCIDENT_TYPES',
  INCIDENT_REPORTS: 'INCIDENT_REPORTS',
  SWMS: 'SWMS',
}

export const MMKV_KEY={
  EMAIL:'EMAIL'
}