export const QUERY_KEY = {
  CURRENT_USER: 'CURRENT_USER',
  ROLES: 'ROLES',
  SITES: 'SITES',
  USERS: 'USERS',
  USERS_BY_PERMISSION: 'USERS_BY_PERMISSION',
  TAKEN_ACTIONS: 'TAKEN_ACTIONS',
  INCIDENT_TYPES: 'INCIDENT_TYPES',
  INCIDENT_REPORT: 'INCIDENT_REPORT',
  INCIDENT_REPORTS: 'INCIDENT_REPORTS',
  SWMS: 'SWMS',
  CHECKLIST: 'CHECKLIST',
  DSRAS: 'DSRAS',
  DSRAS_TODAY: 'DSRAS_TODAY',
  DSRAS_DETAIL: 'DSRAS_DETAIL',
  USER_FILTER_OPTIONS: 'USER_FILTER_OPTIONS',
  INCIDENTS_FILTER_OPTIONS: 'INCIDENTS_FILTER_OPTIONS',
  DSRAS_FILTER_OPTIONS: 'DSRAS_FILTER_OPTIONS',
  JOBS:'JOBS',
  JOB_DETAIL: 'JOB_DETAIL',
  CERTIFICATES: 'CERTIFICATES',
  CERTIFICATE_DETAIL: 'CERTIFICATE_DETAIL',
}

export const MMKV_KEY={
  EMAIL:'EMAIL'
}